### PR TITLE
Port from libunique to GApplication

### LINKED ISSUE #13: Migrate caja-actions to GApplication and/or GtkApplication
Debian has raised the following bug:

- **caja-actions** - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844376

This MATE component needs migrating to GApplication and/or GtkApplication:

- https://developer.gnome.org/gtk3/3.20/gtk-migrating-unique-GtkApplication.html

### PR DESCRIPTION
**Pull request by sc0w**
Fixes #13 

@raveit65 @monsta @lukefromdc please, test the unique instance of `caja-actions-config-tool`

thanks :)

### CODE REVIEW

**Comment by lukefromdc** [comment]
A gtk3 build (only kind possible with GtkApplication) worked fine, and trying to invoke caja-actions-config-tool twice generated this message in a popup dialog box:
"The application is not unique
Another instance of Caja-Actions Configuration Tool is already running
Please switch back to it."
I assume that is the desired behavior?

**Comment by sc0w** [comment]
> I assume that is the desired behavior?

yes, the original code has the same behaviour

**Comment by lukefromdc** [comment]
Than this looks good to go.

**Comment by sc0w** [comment]
now, all is fine, the build is ok without the libunique libraries

:+1:

**Comment by raveit65** [comment]
Thanks for this port :-)
It works fine with gtk3 build.
So GApplication is for gtk2 and gtk3 build?

**Comment by sc0w** [comment]
> So GApplication is for gtk2 and gtk3 build?

yes, you can see my another port to GApplication on mate-netbook:

https://github.com/mate-desktop/mate-netbook/pull/33

**Comment by raveit65** [comment]
Thanks a lot :-)

**Pull request merged**
