### PR TITLE
move to GTK+3 (>= 3.14), drop GTK+2 code and --with-gtk build option

### PR DESCRIPTION
**Pull request by sc0w**
like all the official mate components

### CODE REVIEW

**Comment by raveit65** [comment]
I did already work on it with that branch https://github.com/raveit65/caja-actions/commits/dev-gtk3-only
....but i forgot why i didn't release it :-)

**Comment by sc0w** [comment]
ah ok, I have tested your branch and the build is ok

**Comment by raveit65** [comment]
I think i stopped working there as i wasn't sure about adding support for different file-managers from nautilus-action.
Nautilus-acition does have support for caja now but there is no new release at gnome dl-server with latest changes.
https://git.gnome.org/browse/nautilus-actions/commit/?id=bcc1a347a861fde60225a6bccf278be3b9f436a7
https://download.gnome.org/sources/nautilus-actions/

I think i will merge gkt3-only branch without support for different file-manger if i find some time.

**Comment by sc0w** [comment]
https://git.gnome.org/browse/nautilus-actions/commit/?id=bcc1a347a861fde60225a6bccf278be3b9f436a7

:+1: 

The gnome developers renamed nautilus-actions to filemanager-actions:

https://download.gnome.org/sources/filemanager-actions/

**Comment by raveit65** [comment]
ahh, good finder.

**Comment by raveit65** [comment]
@sc0w 
I just released 1.8.3 (gtk3 only bits)

**Comment by sc0w** [comment]
@raveit65 thanks

do you think caja-actions can be resurrected to the official mate components?

**Comment by raveit65** [comment]
Sure, i am happy if more people help to maintain it.
Depends on what the other guys say.

**Pull request closed without merging**
